<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('pays', function (Blueprint $table) {
            $table->id();
            $table->string('nom', 190)->unique();
            $table->timestamps();
        });

        DB::table('pays')->insertOrIgnore([
                ['site' =>'Maroc'],
                ['site' =>'France'],
                ['site' =>'Afghanistan'],
                ['site' =>'Afrique du Sud'],
                ['site' =>'Albanie'],
                ['site' =>'Algérie'],
                ['site' =>'Allemagne'],
                ['site' =>'Andorre'],
                ['site' =>'Angola'],
                ['site' =>'Anguilla'],
                ['site' =>'Antarctique'],
                ['site' =>'Antigua-et-Barbuda'],
                ['site' =>'Antilles néerlandaises'],
                ['site' =>'Arabie saoudite'],
                ['site' =>'Argentine'],
                ['site' =>'Arménie'],
                ['site' =>'Aruba'],
                ['site' =>'Australie'],
                ['site' =>'Autriche'],
                ['site' =>'Azerbaïdjan'],
                ['site' =>'Bénin'],
                ['site' =>'Bahamas'],
                ['site' =>'Bahreïn'],
                ['site' =>'Bangladesh'],
                ['site' =>'Barbade'],
                ['site' =>'Belau'],
                ['site' =>'Belgique'],
                ['site' =>'Belize'],
                ['site' =>'Bermudes'],
                ['site' =>'Bhoutan'],
                ['site' =>'Biélorussie'],
                ['site' =>'Birmanie'],
                ['site' =>'Bolivie'],
                ['site' =>'Bosnie-Herzégovine'],
                ['site' =>'Botswana'],
                ['site' =>'Brésil'],
                ['site' =>'Brunei'],
                ['site' =>'Bulgarie'],
                ['site' =>'Burkina Faso'],
                ['site' =>'Burundi'],
                ['site' =>'Côte d\'Ivoire'],
                ['site' =>'Cambodge'],
                ['site' =>'Cameroun'],
                ['site' =>'Canada'],
                ['site' =>'Cap-Vert'],
                ['site' =>'Chili'],
                ['site' =>'Chine'],
                ['site' =>'Chypre'],
                ['site' =>'Colombie'],
                ['site' =>'Comores'],
                ['site' =>'Congo'],
                ['site' =>'Corée du Nord'],
                ['site' =>'Corée du Sud'],
                ['site' =>'Costa Rica'],
                ['site' =>'Croatie'],
                ['site' =>'Cuba'],
                ['site' =>'Danemark'],
                ['site' =>'Djibouti'],
                ['site' =>'Dominique'],
                ['site' =>'Égypte'],
                ['site' =>'Émirats arabes unis'],
                ['site' =>'Équateur'],
                ['site' =>'Érythrée'],
                ['site' =>'Espagne'],
                ['site' =>'Estonie'],
                ['site' =>'États-Unis'],
                ['site' =>'Éthiopie'],
                ['site' =>'Finlande'],
                ['site' =>'Géorgie'],
                ['site' =>'Gabon'],
                ['site' =>'Gambie'],
                ['site' =>'Ghana'],
                ['site' =>'Gibraltar'],
                ['site' =>'Grèce'],
                ['site' =>'Grenade'],
                ['site' =>'Groenland'],
                ['site' =>'Guadeloupe'],
                ['site' =>'Guam'],
                ['site' =>'Guatemala'],
                ['site' =>'Guinée'],
                ['site' =>'Guinée équatoriale'],
                ['site' =>'Guinée-Bissau'],
                ['site' =>'Guyana'],
                ['site' =>'Guyane française'],
                ['site' =>'Haïti'],
                ['site' =>'Honduras'],
                ['site' =>'Hong Kong'],
                ['site' =>'Hongrie'],
                ['site' =>'Ile Bouvet'],
                ['site' =>'Ile Christmas'],
                ['site' =>'Ile Norfolk'],
                ['site' =>'Iles Cayman'],
                ['site' =>'Iles Cook'],
                ['site' =>'Iles Féroé'],
                ['site' =>'Iles Falkland'],
                ['site' =>'Iles Fidji'],
                ['site' =>'Iles Géorgie du Sud et Sandwich du Sud'],
                ['site' =>'Iles Heard et McDonald'],
                ['site' =>'Iles Marshall'],
                ['site' =>'Iles Pitcairn'],
                ['site' =>'Iles Salomon'],
                ['site' =>'Iles Svalbard et Jan Mayen'],
                ['site' =>'Iles Turks-et-Caicos'],
                ['site' =>'Iles Vierges américaines'],
                ['site' =>'Iles Vierges britanniques'],
                ['site' =>'Iles des Cocos (Keeling)'],
                ['site' =>'Iles mineures éloignées des États-Unis'],
                ['site' =>'Inde'],
                ['site' =>'Indonésie'],
                ['site' =>'Iran'],
                ['site' =>'Iraq'],
                ['site' =>'Irlande'],
                ['site' =>'Islande'],
                ['site' =>'Palestine'],
                ['site' =>'Italie'],
                ['site' =>'Jamaïque'],
                ['site' =>'Japon'],
                ['site' =>'Jordanie'],
                ['site' =>'Kazakhstan'],
                ['site' =>'Kenya'],
                ['site' =>'Kirghizistan'],
                ['site' =>'Kiribati'],
                ['site' =>'Koweït'],
                ['site' =>'Laos'],
                ['site' =>'Lesotho'],
                ['site' =>'Lettonie'],
                ['site' =>'Liban'],
                ['site' =>'Liberia'],
                ['site' =>'Libye'],
                ['site' =>'Liechtenstein'],
                ['site' =>'Lituanie'],
                ['site' =>'Luxembourg'],
                ['site' =>'Macao'],
                ['site' =>'Madagascar'],
                ['site' =>'Malaisie'],
                ['site' =>'Malawi'],
                ['site' =>'Maldives'],
                ['site' =>'Mali'],
                ['site' =>'Malte'],
                ['site' =>'Mariannes du Nord'],
                ['site' =>'Martinique'],
                ['site' =>'Maurice'],
                ['site' =>'Mauritanie'],
                ['site' =>'Mayotte'],
                ['site' =>'Mexique'],
                ['site' =>'Micronésie'],
                ['site' =>'Moldavie'],
                ['site' =>'Monaco'],
                ['site' =>'Mongolie'],
                ['site' =>'Montserrat'],
                ['site' =>'Mozambique'],
                ['site' =>'Népal'],
                ['site' =>'Namibie'],
                ['site' =>'Nauru'],
                ['site' =>'Nicaragua'],
                ['site' =>'Niger'],
                ['site' =>'Nigeria'],
                ['site' =>'Nioué'],
                ['site' =>'Norvège'],
                ['site' =>'Nouvelle-Calédonie'],
                ['site' =>'Nouvelle-Zélande'],
                ['site' =>'Oman'],
                ['site' =>'Ouganda'],
                ['site' =>'Ouzbékistan'],
                ['site' =>'Pérou'],
                ['site' =>'Pakistan'],
                ['site' =>'Panama'],
                ['site' =>'Papouasie-Nouvelle-Guinée'],
                ['site' =>'Paraguay'],
                ['site' =>'Pays-Bas'],
                ['site' =>'Philippines'],
                ['site' =>'Pologne'],
                ['site' =>'Polynésie française'],
                ['site' =>'Porto Rico'],
                ['site' =>'Portugal'],
                ['site' =>'Qatar'],
                ['site' =>'République centrafricaine'],
                ['site' =>'République démocratique du Congo'],
                ['site' =>'République dominicaine'],
                ['site' =>'République tchèque'],
                ['site' =>'Réunion'],
                ['site' =>'Roumanie'],
                ['site' =>'Royaume-Uni'],
                ['site' =>'Russie'],
                ['site' =>'Rwanda'],
                ['site' =>'Sénégal'],
                ['site' =>'Saint-Christophe-et-Niévès'],
                ['site' =>'Saint-Marin'],
                ['site' =>'Saint-Pierre-et-Miquelon'],
                ['site' =>'Saint-Siège '],
                ['site' =>'Saint-Vincent-et-les-Grenadines'],
                ['site' =>'Sainte-Hélène'],
                ['site' =>'Sainte-Lucie'],
                ['site' =>'Salvador'],
                ['site' =>'Samoa'],
                ['site' =>'Samoa américaines'],
                ['site' =>'Sao Tomé-et-Principe'],
                ['site' =>'Seychelles'],
                ['site' =>'Sierra Leone'],
                ['site' =>'Singapour'],
                ['site' =>'Slovénie'],
                ['site' =>'Slovaquie'],
                ['site' =>'Somalie'],
                ['site' =>'Soudan'],
                ['site' =>'Sri Lanka'],
                ['site' =>'Suède'],
                ['site' =>'Suisse'],
                ['site' =>'Suriname'],
                ['site' =>'Swaziland'],
                ['site' =>'Syrie'],
                ['site' =>'Taïwan'],
                ['site' =>'Tadjikistan'],
                ['site' =>'Tanzanie'],
                ['site' =>'Tchad'],
                ['site' =>'Terres australes françaises'],
                ['site' =>'Territoire britannique de lOcéan Indien'],
                ['site' =>'Thaïlande'],
                ['site' =>'Timor Oriental'],
                ['site' =>'Togo'],
                ['site' =>'Tokélaou'],
                ['site' =>'Tonga'],
                ['site' =>'Trinité-et-Tobago'],
                ['site' =>'Tunisie'],
                ['site' =>'Turkménistan'],
                ['site' =>'Turquie'],
                ['site' =>'Tuvalu'],
                ['site' =>'Ukraine'],
                ['site' =>'Uruguay'],
                ['site' =>'Vanuatu'],
                ['site' =>'Venezuela'],
                ['site' =>'Vietnam'],
                ['site' =>'Wallis-et-Futuna'],
                ['site' =>'Yémen'],
                ['site' =>'Yougoslavie'],
                ['site' =>'Zambie'],
                ['site' =>'Zimbabwe'],
                ['site' =>'ex-République yougoslave de Macédoine'],
                ['site' =>'Monténégro'],
                ['site' =>'Serbie'],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('pays');
    }
};
